name: Build/Push Image and Release Charts
"on":
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setenv
        uses: ortelius/workflow-toolkit/.github/workflows/env-config-workflow.yml@a3e5ee9fed858b51eb6a3b5e78856b5a32c70163
        with:
          gh_head_ref: ${{ github.head_ref }}
          gh_ref_name: ${{ github.ref_name }}
          gh_event_repo_name: ${{ github.event.repository.name }}
          gh_sha: ${{ github.sha }}
          gh_repo: ${{ github.repository }}
          gh_run_number: ${{ github.run_number }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Cosign
        uses: sigstore/cosign-installer@e1523de7571e31dbe865fd2e80c5c7c23ae71eb4 # v3.4.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3
        with:
          version: v0.13.0-rc1

      - name: Login to Quay
        id: login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ steps.setenv.outputs.image_repository }}
          username: ${{ secrets.QUAY_USERID }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and Push Docker Image
        id: build
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5.2.0
        with:
          push: true
          tags: ${{ steps.setenv.outputs.image_repo_tag }}
          platforms: linux/amd64
          attests: type=provenance,type=sbom

      - name: slsa
        uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.10.0
        with:
          image: ${{ steps.setenv.outputs.image_repository }}
          digest: ${{ steps.build.outputs.digest }}
