---
name: Dump

on:
  push:
    branches:
      - main

jobs:
  setenv:
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.env.outputs.short_sha }}
      chart_version: ${{ steps.env.outputs.chart_version }}
      image_version: ${{ steps.env.outputs.image_version }}
      image_tag: ${{ steps.env.outputs.image_tag }}
      image_repo_tag: ${{ steps.env.outputs.image_repo_tag }}
      image_repository: ${{ steps.env.outputs.image_repository }}
      registry: ${{ steps.env.outputs.registry }}
      branch: ${{ steps.env.outputs.branch }}
      compname: ${{ steps.env.outputs.compname }}
      dhurl: ${{ steps.env.outputs.dhurl }}
      gh_handle: ${{ steps.env.outputs.gh_handle }}

    steps:
      - name: Setup Env
        id: env
        uses: ortelius/ms-setenv-action@d4f32967a7dc0cb952c037a5e71ccce5ae7d455f # v1.0.0
        with:
          gh_head_ref: ${{ github.head_ref }}
          gh_ref_name: ${{ github.ref_name }}
          gh_event_repo_name: ${{ github.event.repository.name }}
          gh_sha: ${{ github.sha }}
          gh_repository: ${{ github.repository }}
          gh_run_number: ${{ github.run_number }}

  dump:
    runs-on: ubuntu-latest
    needs: [setenv]

    steps:
      - name: dumpit
        run: |
          echo "${{ github.event.repository.fork }}"
          echo '${{ toJson(github) }}'
          echo '${{ toJson(needs) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(job) }}'
